// Educational books mock data
export const mockBooks = [
  {
    id: "1",
    title: "Introduction to Calculus",
    author: "Dr. Sarah Johnson",
    isbn: "978-0123456789",
    sku: "CAL-MTH-4321",
    category: "mathematics",
    price: 79.99,
    description: "A comprehensive introduction to calculus concepts.",
    publisher: "Academic Press",
    publication_date: "2023-08-15",
    cover_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Physics Fundamentals",
    author: "Dr. Michael Chen",
    isbn: "978-0987654321",
    sku: "PHY-SCI-5678",
    category: "physics",
    price: 89.99,
    description: "Essential concepts in physics for undergraduate students.",
    publisher: "Science Publications",
    publication_date: "2023-09-20",
    cover_image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Biology: Life Sciences",
    author: "Dr. Emily Brown",
    isbn: "978-1234567890",
    sku: "BIO-SCI-9012",
    category: "biology",
    price: 74.99,
    description: "Comprehensive guide to biological sciences.",
    publisher: "Science Press",
    publication_date: "2023-10-05",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Chemistry Essentials",
    author: "Dr. Robert Wilson",
    isbn: "978-2345678901",
    sku: "CHM-SCI-3456",
    category: "chemistry",
    price: 84.99,
    description: "Core concepts in chemistry for college students.",
    publisher: "Academic Books",
    publication_date: "2023-11-15",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Computer Science 101",
    author: "Dr. Lisa Zhang",
    isbn: "978-3456789012",
    sku: "CSC-TEC-7890",
    category: "computer_science",
    price: 69.99,
    description: "Introduction to computer science principles.",
    publisher: "Tech Education",
    publication_date: "2023-12-01",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Rest of the mock data remains the same
export const mockStores = [
  {
    id: "1",
    name: "Campus Bookstore",
    address: "123 University Ave",
    status: "active",
    manager_id: "1",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Add sales mock data
export const mockSalesData = {
  today: {
    total: 12500,
    percentChange: 15,
    orders: 45,
    averageOrder: 277.78,
  },
  hourlyTrends: [
    { hour: "00:00", sales: 120 },
    { hour: "01:00", sales: 90 },
    { hour: "02:00", sales: 75 },
    { hour: "03:00", sales: 60 },
    { hour: "04:00", sales: 80 },
    { hour: "05:00", sales: 90 },
    { hour: "06:00", sales: 150 },
    { hour: "07:00", sales: 200 },
    { hour: "08:00", sales: 250 },
    { hour: "09:00", sales: 300 },
    { hour: "10:00", sales: 350 },
    { hour: "11:00", sales: 400 },
  ],
  monthlyTrends: [
    { month: "Jan", sales: 45000, orders: 1200 },
    { month: "Feb", sales: 52000, orders: 1350 },
    { month: "Mar", sales: 49000, orders: 1400 },
    { month: "Apr", sales: 47000, orders: 1250 },
    { month: "May", sales: 55000, orders: 1500 },
    { month: "Jun", sales: 60000, orders: 1600 },
  ],
  categoryDistribution: [
    { name: "Mathematics", value: 30, sales: 38000 },
    { name: "Physics", value: 25, sales: 32000 },
    { name: "Biology", value: 20, sales: 28000 },
    { name: "Chemistry", value: 15, sales: 22000 },
    { name: "Computer Science", value: 10, sales: 18000 },
  ],
};

// Add inventory mock data
export const mockInventory = [
  {
    id: "1",
    book_id: "1",
    store_id: "1",
    quantity: 150,
    min_stock_level: 20,
    max_stock_level: 200,
    status: "in_stock",
    rack_location: "A-01-R1-S2-03",
    last_restock_date: "2024-03-15",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    access_frequency: "high",
    category_optimization: "mathematics-core",
  },
  {
    id: "2",
    book_id: "2",
    store_id: "1",
    quantity: 15,
    min_stock_level: 25,
    max_stock_level: 150,
    status: "low_stock",
    rack_location: "B-02-R3-S1-05",
    last_restock_date: "2024-03-10",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    access_frequency: "medium",
    category_optimization: "physics-core",
  },
];

// Add rack analytics mock data
export const mockRackAnalytics = {
  utilization: {
    total_spaces: 500,
    occupied: 342,
    available: 158,
    utilization_rate: 68.4,
  },
  popular_sections: [
    { section: "Mathematics", utilization: 85, frequency: "high" },
    { section: "Physics", utilization: 72, frequency: "medium" },
    { section: "Biology", utilization: 65, frequency: "medium" },
  ],
  category_distribution: [
    { category: "Mathematics", count: 150, optimization_score: 92 },
    { category: "Physics", count: 120, optimization_score: 88 },
    { category: "Biology", count: 80, optimization_score: 85 },
  ],
  optimization_suggestions: [
    {
      id: "1",
      current_location: "A-01-R1-S2-03",
      suggested_location: "A-01-R1-S1-01",
      reason: "High frequency access for core mathematics texts",
      priority: "high",
    },
    {
      id: "2",
      current_location: "B-02-R3-S1-05",
      suggested_location: "A-02-R2-S2-03",
      reason: "Physics section consolidation",
      priority: "medium",
    },
  ],
};
